export const TWEET_LIST = {
  created_at: "Sat Jun 23 05: 24: 50 +0000 2018",
  id: 1010393219274698800,
  id_str: "1010393219274698752",
  text: "RT @eri_sai: 息子よ...問題を読みなさい https: //t.co/qedW1jUMRK",
  truncated: false,
  entities: {
    hashtags: [],
    symbols: [],
    user_mentions: [[Object]],
    urls: [],
    media: [[Object]]
  },
  extended_entities: {
    media: [[Object]]
  },
  source:
    '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 94733985,
    id_str: "94733985",
    name: "zonbi tamago",
    screen_name: "zonbitamago",
    location: "北海道はでっかいどう",
    description: "ぞんたま　zon bass trombone hokkaido university",
    url: "http: //t.co/8HrDj5V94l",
    entities: {
      url: [Object],
      description: [Object]
    },
    protected: false,
    followers_count: 104,
    friends_count: 116,
    listed_count: 5,
    created_at: "Sat Dec 05 05: 36: 45 +0000 2009",
    favourites_count: 212,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 2460,
    lang: "ja",
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: "EDECE9",
    profile_background_image_url:
      "http: //abs.twimg.com/images/themes/theme3/bg.gif",
    profile_background_image_url_https:
      "https: //abs.twimg.com/images/themes/theme3/bg.gif",
    profile_background_tile: false,
    profile_image_url:
      "http: //pbs.twimg.com/profile_images/928067133/STIL0017_normal.jpg",
    profile_image_url_https:
      "https: //pbs.twimg.com/profile_images/928067133/STIL0017_normal.jpg",
    profile_banner_url:
      "https: //pbs.twimg.com/profile_banners/94733985/1353817301",
    profile_link_color: "088253",
    profile_sidebar_border_color: "D3D2CF",
    profile_sidebar_fill_color: "E3E2DE",
    profile_text_color: "634047",
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: false,
    default_profile_image: false,
    following: false,
    follow_request_sent: false,
    notifications: false,
    translator_type: "none"
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweeted_status: {
    created_at: "Fri Jun 22 11: 51: 50 +0000 2018",
    id: 1010128223022149600,
    id_str: "1010128223022149632",
    text: "息子よ...問題を読みなさい https: //t.co/qedW1jUMRK",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
      media: [Array]
    },
    extended_entities: {
      media: [Array]
    },
    source: '<a href="http://www.echofon.com/" rel="nofollow">Echofon</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 95228378,
      id_str: "95228378",
      name: "ERI",
      screen_name: "eri_sai",
      location: "Tokyo, JP",
      description: "Niigata / Portland, OR / Tokyo / 英語忘れそう/ 働く1児の母",
      url: null,
      entities: [Object],
      protected: false,
      followers_count: 1073,
      friends_count: 1983,
      listed_count: 11,
      created_at: "Mon Dec 07 16: 09: 42 +0000 2009",
      favourites_count: 652,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: false,
      statuses_count: 8417,
      lang: "ja",
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "FFF04D",
      profile_background_image_url:
        "http: //abs.twimg.com/images/themes/theme19/bg.gif",
      profile_background_image_url_https:
        "https: //abs.twimg.com/images/themes/theme19/bg.gif",
      profile_background_tile: false,
      profile_image_url:
        "http: //pbs.twimg.com/profile_images/444498056856104960/j-kvZZN9_normal.jpeg",
      profile_image_url_https:
        "https: //pbs.twimg.com/profile_images/444498056856104960/j-kvZZN9_normal.jpeg",
      profile_link_color: "0099CC",
      profile_sidebar_border_color: "FFF8AD",
      profile_sidebar_fill_color: "F6FFD1",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none"
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 110236,
    favorite_count: 315764,
    favorited: true,
    retweeted: true,
    possibly_sensitive: false,
    lang: "ja"
  },
  is_quote_status: false,
  retweet_count: 110236,
  favorite_count: 0,
  favorited: true,
  retweeted: true,
  possibly_sensitive: false,
  lang: "ja"
};
